### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by etetteh** [pytorch/ignite#1594] opened 2021-01-30 16:04 UTC
I am using a custom batch function
```
def custom_prepare_batch(batch, device, non_blocking):
    x, y = batch["img"], batch["lab"]
    return (
        convert_tensor(x, device=device, non_blocking=non_blocking),
        convert_tensor(y, device=device, non_blocking=non_blocking),
    )
```
and my processing function is as follows:
```
def train_function(unused_engine, batch):
        images, targets = custom_prepare_batch(batch, device=device, non_blocking=True)
#         images, targets = batch["img"], batch["lab"]
    
        model.train()
        optimizer.zero_grad()

        y_preds = model(images)

        if agreement_threshold > 0.0:
            # The "batch_size" in this function refers to the batch size per env
            # Since we treat every example as one env, we should set the parameter
            # n_agreement_envs equal to batch size
            mean_loss, masks = and_mask_utils.get_grads(
                agreement_threshold=agreement_threshold,
                batch_size=1,
                loss_fn=criterion,
                n_agreement_envs=batch_size,
                params=optimizer.param_groups[0]['params'],
                output=y_preds,
                target=targets,
                method="and_mask",
                scale_grad_inverse_sparsity=scale_grad_inverse_sparsity,
            )
        else:
            mean_loss = criterion(y_pred, y)
            mean_loss.backward()

        optimizer.step()

        return y_preds, targets
```
and I am also passing the custom batch function as follows
`train_evaluator = create_supervised_evaluator(model, device=device, non_blocking=True, prepare_batch=custom_prepare_batch)`

when I run my code 
```
trainer_rng = np.random.RandomState()
trainer.run(next(iter(train_loader)), max_epochs=2,
                seed=trainer_rng.randint(2 ** 32))
```
I get the error

```
Current run is terminating due to exception: string indices must be integers.
Engine run is terminating due to exception: string indices must be integers.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-099d5afd435f> in <module>
     32 
     33 trainer_rng = np.random.RandomState()
---> 34 trainer.run(next(iter(train_loader)), max_epochs=2,
     35                 seed=trainer_rng.randint(2 ** 32))

~/.conda/envs/mila/lib/python3.8/site-packages/ignite/engine/engine.py in run(self, data, max_epochs, epoch_length, seed)
    689 
    690         self.state.dataloader = data
--> 691         return self._internal_run()
    692 
    693     @staticmethod

~/.conda/envs/mila/lib/python3.8/site-packages/ignite/engine/engine.py in _internal_run(self)
    760             self._dataloader_iter = None
    761             self.logger.error("Engine run is terminating due to exception: %s.", str(e))
--> 762             self._handle_exception(e)
    763 
    764         self._dataloader_iter = None

~/.conda/envs/mila/lib/python3.8/site-packages/ignite/engine/engine.py in _handle_exception(self, e)
    465             self._fire_event(Events.EXCEPTION_RAISED, e)
    466         else:
--> 467             raise e
    468 
    469     @property

~/.conda/envs/mila/lib/python3.8/site-packages/ignite/engine/engine.py in _internal_run(self)
    728                     self._setup_engine()
    729 
--> 730                 time_taken = self._run_once_on_dataset()
    731                 # time is available for handlers but must be update after fire
    732                 self.state.times[Events.EPOCH_COMPLETED.name] = time_taken

~/.conda/envs/mila/lib/python3.8/site-packages/ignite/engine/engine.py in _run_once_on_dataset(self)
    826         except Exception as e:
    827             self.logger.error("Current run is terminating due to exception: %s.", str(e))
--> 828             self._handle_exception(e)
    829 
    830         return time.time() - start_time

~/.conda/envs/mila/lib/python3.8/site-packages/ignite/engine/engine.py in _handle_exception(self, e)
    465             self._fire_event(Events.EXCEPTION_RAISED, e)
    466         else:
--> 467             raise e
    468 
    469     @property

~/.conda/envs/mila/lib/python3.8/site-packages/ignite/engine/engine.py in _run_once_on_dataset(self)
    809                 self.state.iteration += 1
    810                 self._fire_event(Events.ITERATION_STARTED)
--> 811                 self.state.output = self._process_function(self, self.state.batch)
    812                 self._fire_event(Events.ITERATION_COMPLETED)
    813 

<ipython-input-12-0c14fe7efe33> in train_function(unused_engine, batch)
      1 def train_function(unused_engine, batch):
----> 2         images, targets = custom_prepare_batch(batch, device=device, non_blocking=True)
      3 #         images, targets = batch["img"], batch["lab"]
      4 
      5         model.train()

<ipython-input-11-206b9292729e> in custom_prepare_batch(batch, device, non_blocking)
      1 def custom_prepare_batch(batch, device, non_blocking):
----> 2     x, y = batch["img"], batch["lab"]
      3     return (
      4         convert_tensor(x, device=device, non_blocking=non_blocking),
      5         convert_tensor(y, device=device, non_blocking=non_blocking),

TypeError: string indices must be integers
```

Kindly, assist me. Thank you.

**Comment by vfdev-5** [comment] 2021-01-30 16:13
I think the issue is related to the way you pass the data: `next(iter(train_loader))` which looks a bit strange. Maybe, you can pass directly `train_loader` ?

Btw: looks like you are using v0.3.0, please think to [migrate to v0.4.2](https://github.com/pytorch/ignite/wiki/Migration-note-:-v0.3.0--to--v0.4.0)

**Comment by etetteh** [comment] 2021-01-30 18:31
Thank you. The code ran successfully after implementing your suggestions.

**Comment by etetteh** [comment] 2021-01-30 18:34
However, I ended up with nans and and `trainer.state.metrics` was empty.

I used the previous suggestions from

```
def ot_per_task_loss(output, task_index):
    y_pred, y = output
    # Remove NaNs with mask
    task_output = y_pred[:, task_index]
    task_target = y[:,task_index]
    mask = ~torch.isnan(task_target)
    task_output = torch.sigmoid(task_output[mask])
    task_target = task_target[mask]
    return task_output, task_target
```
and 
```
for i in range(train_data.labels.shape[1]):
    loss_per_task["task_{}_loss".format(i)] = Loss(loss_fn=criterion, output_transform=partial(ot_per_task_loss, task_index=i))
```
The original code has conditions that ignore the nans in the output, I am not able to adapt it to ignite...
```
def valid_test_epoch(name, epoch, model, device, data_loader, criterion, limit=None):
    model.eval()

    avg_loss = []
    task_outputs={}
    task_targets={}
    for task in range(data_loader.dataset[0]["lab"].shape[0]):
        task_outputs[task] = []
        task_targets[task] = []
        
    with torch.no_grad():
        t = tqdm(data_loader)
        for batch_idx, samples in enumerate(t):

            if limit and (batch_idx > limit):
                print("breaking out")
                break
            
            images = samples["img"].to(device)
            targets = samples["lab"].to(device)

            outputs = model(images)
            
            loss = torch.zeros(1).to(device).double()
            for task in range(targets.shape[1]):
                task_output = outputs[:,task]
                task_target = targets[:,task]
                mask = ~torch.isnan(task_target)
                task_output = task_output[mask]
                task_target = task_target[mask]
                if len(task_target) > 0:
                    loss += criterion(task_output.double(), task_target.double())
                
                task_outputs[task].append(task_output.detach().cpu().numpy())
                task_targets[task].append(task_target.detach().cpu().numpy())

            loss = loss.sum()
            
            avg_loss.append(loss.detach().cpu().numpy())
            t.set_description(f'Epoch {epoch + 1} - {name} - Loss = {np.mean(avg_loss):4.4f}')
            
        for task in range(len(task_targets)):
            task_outputs[task] = np.concatenate(task_outputs[task])
            task_targets[task] = np.concatenate(task_targets[task])
    
        task_aucs = []
        for task in range(len(task_targets)):
            if len(np.unique(task_targets[task]))> 1:
                task_auc = sklearn.metrics.roc_auc_score(task_targets[task], task_outputs[task])
                #print(task, task_auc)
                task_aucs.append(task_auc)
            else:
                task_aucs.append(np.nan)

    task_aucs = np.asarray(task_aucs)
    auc = np.mean(task_aucs[~np.isnan(task_aucs)])
    print(f'Epoch {epoch + 1} - {name} - Avg AUC = {auc:4.4f}')

    return auc, task_aucs, task_outputs, task_targets
```

**Comment by vfdev-5** [comment] 2021-01-30 20:09
> The original code has conditions that ignore the nans in the output,

Well, I'm not sure to fully understand the code. In order to rewrite it using Ignite, you can think of the following:
- define evaluator as a custom inference step and Engine 
```python

def infer_step(engine, batch):
    with torch.no_grad():
            images = samples["img"].to(device)
            targets = samples["lab"].to(device)

            outputs = model(images)
            
            task_outputs = []
            task_targets = []
            loss = torch.zeros(1).to(device).double()
            for task in range(targets.shape[1]):
                task_output = outputs[:,task]
                task_target = targets[:,task]
                mask = ~torch.isnan(task_target)
                task_output = task_output[mask]
                task_target = task_target[mask]
                if len(task_target) > 0:
                    loss += criterion(task_output.double(), task_target.double())
                
                task_outputs.append(task_output.detach().cpu().numpy())
                task_targets.append(task_target.detach().cpu().numpy())

            loss = loss.sum()

    return {
         "loss": loss,
         "preds": task_outputs,
         "targets": task_targets,
    }

evaluator = Engine(infer_step)
```

- use `output_transform` to adapt output dictionary (with "loss", "preds", "targets" keys) for metric class
```python

def ot_get_loss(output):
     return output["loss"]

from ignite.metrics import Average

avg_loss = Average(output_transform=ot_get_loss)
avg_loss.attach(evaluator, 'avg_loss')
```
See for details : https://pytorch.org/ignite/metrics.html#ignite.metrics.Average

Same can be done for [`EpochMetric`](https://pytorch.org/ignite/metrics.html#ignite.metrics.EpochMetric) and specify your logic inside `compute_fn` (instead of ROC_AUC metric due to the way you insert nan values):
```python
def ot_get_preds_targets_per_task(output, task):
     return output["preds"][task], output["targets"][task] 

def compute_roc_auc(task_outputs, task_targets):
     task_targets = task_targets.cpu().numpy()
     task_outputs = task_outputs.cpu().numpy()
     if len(np.unique(task_targets))> 1:
          return sklearn.metrics.roc_auc_score(task_targets, task_outputs)
     else:
          return np.nan

for i in range(number_tasks):
     m = EpochMetric(compute_roc_auc, output_transform=partial(ot_get_preds_targets_per_task, task=i), check_compute_fn=False)
     m.attach(evaluator, f"roc_auc_{i}")
```

- finally compute average roc auc on evaluation completed event:
```python
@evaluator.on(Events.COMPLETED)
def compute_avg_roc_auc():
     metrics = evaluator.state.metrics
     task_aucs = np.asarray([metrics[f"roc_auc_{i}"] for i in range(number_tasks)])
     metrics["total_auc"] = np.mean(task_aucs[~np.isnan(task_aucs)])
```

Hope this helps!

Please, see also https://pytorch.org/ignite/concepts.html to understand better how things work in ignite.
And please leave a feedback if something is not clear in our docs.

**Comment by etetteh** [comment] 2021-01-30 20:57
Thank you. I will look at it and give you feedback

**Comment by etetteh** [comment] 2021-02-02 00:50
EpochMetric throws the error `AttributeError: 'numpy.ndarray' object has no attribute 'ndimension'`.
And even when, I try torch.Tensor(array), I still get the same error

**Comment by etetteh** [comment] 2021-02-02 07:25
I managed to get it working in a way. I edited the epoch_metric.py file from the repo to make it to accept the ndarray, before converting to torch.Tensor

**Comment by vfdev-5** [comment] 2021-02-02 12:14
> EpochMetric throws the error `AttributeError: 'numpy.ndarray' object has no attribute 'ndimension'`, because the compute_fn expects a torch.tensor object
> And even when, I try torch.Tensor(array), I still get the same error

Maybe, your torch version is a bit old ?

**Comment by vfdev-5** [comment] 2021-02-02 12:15
Let me close this issue as solved. Feel free to open new issue if you have other questions. You can also use GitHub Discussions for questions as well.

**Closed by vfdev-5** 2021-02-02 12:15 UTC
Labels: question
