### ISSUE TITLE
Custom metrics derived from EpochMetric assumed to be for classification

### ISSUE THREAD

**Issue by nsinenian** [pytorch/ignite#1723] opened 2021-03-01 19:06 UTC
## 🐛 Bug description
I am using a NN for a regression problem. For this problem, I have a custom metric derived from `EpochMetric`.  Consider the trivial metric below for illustrative purposes:

    class RawOutput(EpochMetric):
        def __init__(self,output_transform=lambda x: x):
            super(RawOutput, self).__init__(self.raw_fn, output_transform=output_transform)
            
        def raw_fn(self,y_preds,y_targets):
            y_true = y_targets.numpy()
            y_pred = y_preds.numpy()
            return (y_pred, y_true)

This metric simply accumulates the ground truth and prediction values.  It will throw an exception because `y_true` is not 0 or 1; it fails certain internal tests in Ignite, which suggests that `EpochMetric` is implicitly designed only to work for classification tasks (I assume this is not the intention).

Currently, the workaround is to use a transformation and to round the ground truth, but if you actually want the labeled value you can't use it in your metric (e.g., to calculate MSE or some other regression parameter).

## Environment

- PyTorch Version (e.g., 1.4): 1.7.1
- Ignite Version (e.g., 0.3.0): 0.4.2
- OS (e.g., Linux): macOS
- How you installed Ignite (`conda`, `pip`, source): `pip`
- Python version: 3.8
- Any other relevant information:

**Comment by ahmedo42** [comment] 2021-03-01 19:30
Hi , Are you doing  multioutput regression ?  what is the shape of your output? , usually this error happens because if your target shape is `(batch size , n_classes)` , then it's as if you are doing classification

**Comment by vfdev-5** [comment] 2021-03-01 20:30
@nsinenian thanks for reporting! Yes, that's true and we'd like to make it more generic, here related issue: https://github.com/pytorch/ignite/issues/1209

There is also https://github.com/pytorch/ignite/blob/007d320150fa915d7ac8757ddb586aaa9c427682/ignite/contrib/metrics/regression/_base.py#L57

which get rids of this binary target requirement.

**Comment by vfdev-5** [comment] 2021-05-15 14:01
Fixed by #1748

**Closed by vfdev-5** 2021-05-15 14:01 UTC
Labels: duplicate, enhancement, help wanted, module: metrics
