### ISSUE TITLE
Issues with welcome workflow

### ISSUE THREAD

**Issue by rushabh-v** [pytorch/ignite#1844] opened 2021-03-22 07:57 UTC
## 🐛 Bug description
There are two issues with the welcome workflow:
1. It fails with "Error: Resource not accessible by integration" (refer to the attached image).

Solution: Replace `pull_request` with `pull_request_target` [on this line](https://github.com/pytorch/ignite/blob/c955f3c4a8a1d9c4047d700097f802b38c89e358/.github/workflows/welcome.yml#L3).

-----------------
2. The text is not being formatted as properly and also the link to the contributions guide is not working because of the `).` at the end (refer to the attached image).

My analysis: I checked the workflow, it uses [actions/first-interaction](https://github.com/actions/first-interaction), and that uses typescript's `console.log` for rendering the text. And TTBOMK, it's not possible to do formatting with `console.log`.

Solution: Remove the markdown style formatting and pass simple strings.

---------------
![image](https://user-images.githubusercontent.com/46084304/111957521-1d2b9600-8b12-11eb-9e81-5f5b35301b76.png)

I'll open a PR to fix this.

**Comment by rushabh-v** [comment] 2021-03-22 08:08
>Thank you for opening your First Issue!
We appreciate a lot of user's feedback on what we are doing!
If you'd like to contribute to the project, please check out our Contributing Guide.

Okay, it looks like I was facing the second issue because the workflow was failing. Only fixing issue 1 will fix issue 2 in that case.

**Comment by trsvchn** [comment] 2021-03-22 09:31
@rushabh-v Thank you for your bug report! Yes, we are working on this workflow right now and decided temporary turn off, because of unexpected behavior like this.

**Comment by rushabh-v** [comment] 2021-03-22 10:10
Okay, should I close #1845 then?

**Comment by trsvchn** [comment] 2021-03-22 10:12
@rushabh-v Yes, please close it. Thanks for understanding!

**Closed** 2021-03-22 10:14 UTC
