### ISSUE TITLE
DataLoader crash during training

### ISSUE THREAD

**Issue by Nic-Ma** [pytorch/ignite#1610] opened 2021-02-04 11:55 UTC
## ❓ Questions/Help/Support

Hi @vfdev-5 ,

We already internally released some MONAI workflow examples to users, and several people reported this DataLoader issue:
https://discuss.pytorch.org/t/data-loader-crashes-during-training-something-to-do-with-multiprocessing-in-docker/4379
I know it may be not related to ignite workflow, but I don't know how to fix it... Have you encountered it before?

Thanks.

**Comment by vfdev-5** [comment] 2021-02-04 12:05
Hi @Nic-Ma , yes the issues with dataloader can be tricky. I would try the following checks if the issue is reproducible:
- `--shm-size 16G` if run using docker (I remember we already disscussed that previously and you had another option to use)
- to try ensure that it is not data problem and switch off MP with`num_workers=0`
- if using DDP with spawn, try to run on a single proc to see if related

**Comment by Nic-Ma** [comment] 2021-02-04 12:22
Hi @vfdev-5 ,

Thanks for your suggestions.
1. We already set `--ipc=host`, still got the issue, can `--shm-size 16G` be even better than `--ipc=host`?
2. `num_workers=0` can fix the issue I think, but it's not a good solution because we really need workers for performance.

Thanks.

**Comment by vfdev-5** [comment] 2021-02-04 13:34
> We already set --ipc=host, still got the issue, can --shm-size 16G be even better than --ipc=host?

Probably, should have the same effect.

> num_workers=0 can fix the issue I think, but it's not a good solution because we really need workers for performance.

Yes, it is not a solution, but just to see whether there is no issue in reading/transforming/batching the data...

**Comment by yhwen** [comment] 2021-02-04 14:29
We already tested it with num_workers=0. Same error still happened.

**Comment by vfdev-5** [comment] 2021-02-04 15:02
@yhwen thanks for joining. Do you think if we could elaborate a reproducible code snippet of the issue or can you share your code ?

**Comment by yhwen** [comment] 2021-02-04 16:01
This issue happens pretty randomly. I am not sure if we can produce an example code to consistently produce the issue. We have multiple people experience the same error from different model training. Sometimes the error happened at the end of epoch. Sometimes it happened in the middle of epoch after several iterations. Most of the times, the training process just silently crashed without give stack trace. It seems if we have more training clients access the dataset at the same time, the issue happened more frequently.

**Comment by vfdev-5** [comment] 2021-02-04 16:15
Maybe, you could check if it is related to the data access issue, for example, if you replace real data fetching by creating random data or with 1 batch of data samples and see if you still see dataloader crashing ...

**Comment by vfdev-5** [comment] 2021-02-11 20:37
Let me close the issue as it is unrelated to ignite. Feel free to give more details and share your thoughts on the topic. Thanks

**Closed by vfdev-5** 2021-02-11 20:37 UTC
Labels: question
