### ISSUE TITLE
ignite/examples/mnist/mnist.py throwing error out of the box just fyi

### ISSUE THREAD

**Issue by nbcmguarin0** [pytorch/ignite#709] opened 2020-01-20 22:44 UTC
Traceback (most recent call last):
  File "ignite_tester.py", line 118, in <module>
    run(args.batch_size, args.val_batch_size, args.epochs, args.lr, args.momentum, args.log_interval)
  File "ignite_tester.py", line 68, in run
    @trainer.on(Events.ITERATION_COMPLETED(every=log_interval))
TypeError: 'Events' object is not callable

**Comment by vfdev-5** [comment] 2020-01-20 22:46
Duplicate of https://github.com/pytorch/ignite/issues/687

**Closed by vfdev-5** 2020-01-20 22:46 UTC
Labels: duplicate
