### ISSUE TITLE
Circular import error for ignite.metrics.loss

### ISSUE THREAD

**Issue by samsepiol21** [pytorch/ignite#2830] opened 2023-01-24 18:57 UTC
## 🐛 Bug description

Every time I try to import ignite.metrics.loss it gives me a circular import error.

Simply add ```import ignite.metrics.loss```

```python
import ignite.metrics.loss

if __name__ == '__main__':
    print("test")
```
```
Traceback (most recent call last):
  File "D:/Bachelor Arbeit/AudioCaption-master/test.py", line 1, in <module>
    import ignite.metrics.loss
  File "C:\Program Files\Python38\lib\site-packages\ignite\metrics\__init__.py", line 1, in <module>
    from ignite.metrics.accumulation import Average, GeometricAverage, VariableAccumulation
  File "C:\Program Files\Python38\lib\site-packages\ignite\metrics\accumulation.py", line 7, in <module>
    from ignite.metrics.metric import Metric, reinit__is_reduced, sync_all_reduce
  File "C:\Program Files\Python38\lib\site-packages\ignite\metrics\metric.py", line 10, in <module>
    from ignite.engine import CallableEventWithFilter, Engine, Events
  File "C:\Program Files\Python38\lib\site-packages\ignite\engine\__init__.py", line 10, in <module>
    from ignite.metrics import Metric
ImportError: cannot import name 'Metric' from partially initialized module 'ignite.metrics' (most likely due to a circular import) (C:\Program Files\Python38\lib\site-packages\ignite\metrics\__init__.py)

Process finished with exit code 1
```

I would expect the class to import the package.

## Environment

- PyTorch Version (1.13.1):
- Ignite Version (0.4.10):
- OS (Windows 10):
- How you installed Ignite (`pip`, with the Pycharm interpreter):
- Python version: 3.8
- Any other relevant information:

**Comment by vfdev-5** [comment] 2023-01-24 19:32
Thanks for the report @samsepiol21 !
Let me check the details of the problem, meanwhile you can import working metric class `Loss` :
```
from ignite.metrics import Loss
```
Hope this helps

**Comment by samsepiol21** [comment] 2023-01-24 20:12
I get the same error with this import

**Comment by vfdev-5** [comment] 2023-01-24 21:16
@samsepiol21 I can't reproduce the issue on linux and macosx. I'll try on a windows VM but this seems very weird if `from ignite.metrics import Loss` does not work for you ...
Can you show:
```
pip --version
pip list | grep torch
```

Does it work outside Pycharm interpreter ?

**Comment by samsepiol21** [comment] 2023-01-24 21:24
pip 22.3.1
'grep' is not recognized as an internal or external command,
operable program or batch file.

I tried these 2 comands in the cmd terminal

**Comment by samsepiol21** [comment] 2023-01-24 21:26
Would this problem dissapear on a different machine or OS ? so the code could work on linux ? @vfdev-5

**Comment by vfdev-5** [comment] 2023-01-24 21:28
yeah, sorry, I forgot about windows constrain...

> Would this problem dissapear on a different machine or OS ? so the code could work on linux ? @vfdev-5

yes, Ignite works in general on linux, macosx and windows. We have CI running tests on these 3 OS...

**Comment by vfdev-5** [comment] 2023-01-24 22:51
@samsepiol21 it also works in my Windows 10 VM using miniconda3 and python 3.8. Can you try to setup python via miniconda and install pytorch and ignite there and check ?

**Comment by samsepiol21** [comment] 2023-01-24 23:09
If I change the interpreter in pycharm to python 3.9, which is installed from the microsoft store, instead of using the python 3.8 system interpreter, then the error doesn't happen.

**Comment by vfdev-5** [comment] 2023-01-24 23:25
Sounds good! Also, it is better to use a virtual env or conda env instead of system python.
Let's close the issue as solved, feel free to reopen if needed.

**Closed by vfdev-5** 2023-01-24 23:25 UTC
