### ISSUE TITLE
Replace RuntimeError with ModuleNotFoundError in contribute handlers

### ISSUE THREAD

**Issue by louis-she** [pytorch/ignite#2743] opened 2022-10-18 01:58 UTC
Some contribute handlers rely on third-party tools not installed alone with ignite. So there usually will be an import error when users use them for the first time. Some of the import errors raised are `RuntimeError`, instead, we want it to be a more specific error type like `ModuleNotFoundError`.

We should replace all the manually raised `RuntimeError` with `ModuleNotFoundError` when some package can not be imported in third-party contribute handlers.

reference: https://github.com/pytorch/ignite/pull/2742#discussion_r997187850

**Comment by aryanlath** [comment] 2022-10-18 10:40
Hi! Can you assign this issue to me?

**Comment by vfdev-5** [comment] 2022-10-18 10:41
@aryanlath please go ahead and send a PR with the fix

**Comment by aryanlath** [comment] 2022-10-18 10:45
I have sent a PR. Can you kindly check whether the issue is resolved as you wanted?

**Closed** 2022-10-23 21:36 UTC
Labels: help wanted, good first issue, Hacktoberfest
