### ISSUE TITLE
CPU conda package

### ISSUE THREAD

**Issue by jamesmyatt** [pytorch/ignite#485] opened 2019-04-09 15:46 UTC
Is there any chance of a conda package that depends on pytorch-cpu instead? Or am I missing something?

**Comment by vfdev-5** [comment] 2019-04-09 15:56
@jamesmyatt in this case, probably, you can install `pytorch-cpu` at first and then install `ignite` without dependencies:
```bash
conda install pytorch-cpu -c pytorch
conda install ignite -c pytorch --no-deps
```
HTH

**Comment by jamesmyatt** [comment] 2019-04-11 14:22
Does that work in an environment.yml file? i.e. can I add `pytorch::ignite --no-deps`?

**Comment by vfdev-5** [comment] 2019-04-11 14:52
@jamesmyatt probably your issue is a duplicate of https://github.com/conda/conda/issues/7911
I think there is no flag like that in yml. Even if you install packages like proposed above and then export  the environment into `yml`, it is not possible to create new environment with `pytorch-cpu` and `ignite` that does not bring `pytorch`...

**Comment by jamesmyatt** [comment] 2019-04-11 16:15
Agreed. I think it's the same as that conda issue.

**Comment by vfdev-5** [comment] 2019-04-13 17:50
@jamesmyatt the following yaml can probably solve your problem:
```yaml
name: pytorch-ignite-cpu
channels:
  - pytorch
dependencies:
  - python=3.6
  - pip:    
    - https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
    - torchvision
    - pytorch-ignite
```

**Comment by vfdev-5** [comment] 2019-04-21 19:49
@jamesmyatt I'll close the issue as solved (see the solution in the previous message). Feel free to reopen if needed.

**Closed by vfdev-5** 2019-04-21 19:49 UTC
Labels: question
