### ISSUE TITLE
[CI] Doc test is failing

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2850] opened 2023-02-06 09:15 UTC
We have somehow doctest ci job failing right now. The failure happens with the following code snippet from our docs: 
- https://pytorch.org/ignite/generated/ignite.contrib.metrics.PrecisionRecallCurve.html

```
 **********************************************************************
File "../../ignite/contrib/metrics/precision_recall_curve.py", line ?, in default
Failed example:
    y_pred = torch.tensor([0.0474, 0.5987, 0.7109, 0.9997])
    y_true = torch.tensor([0, 0, 1, 1])
    prec_recall_curve = PrecisionRecallCurve()
    prec_recall_curve.attach(default_evaluator, 'prec_recall_curve')
    state = default_evaluator.run([[y_pred, y_true]])

    print("Precision", [round(i, 4) for i in state.metrics['prec_recall_curve'][0].tolist()])
    print("Recall", [round(i, 4) for i in state.metrics['prec_recall_curve'][1].tolist()])
    print("Thresholds", [round(i, 4) for i in state.metrics['prec_recall_curve'][2].tolist()])
Expected:
    Precision [1.0, 1.0, 1.0]
    Recall [1.0, 0.5, 0.0]
    Thresholds [0.7109, 0.9997]
Got:
    Precision [0.5, 0.6667, 1.0, 1.0, 1.0]
    Recall [1.0, 1.0, 1.0, 0.5, 0.0]
    Thresholds [0.0474, 0.5987, 0.7109, 0.9997]
```
- https://github.com/pytorch/ignite/actions/runs/4099985910/jobs/7074343114

### How to help with this issue

You need to do some detective work:
- Reproduce the issue locally
- Try to figure out which result is correct: "Expected" or "Got"
- Try to figure out why it started to happen: maybe sklearn version updated ? Previously, for example Jan 18, doctest was passing: https://github.com/pytorch/ignite/actions/runs/3894024421/jobs/6647420435
- Report here your findings and propose a way to solve the issue

**Comment by pacificdragon** [comment] 2023-02-06 19:54
Hi @vfdev-5,

Here are my findings :

- Expected result is correct
- It started happening when scipy version got upgraded from 1.7.3 to 1.10.0.

The proposed way to solve:

1. Since it's a dependency on an external library we can configure in the requirements file of this project to use scipy version 1.7.3.

**Comment by vfdev-5** [comment] 2023-02-06 20:30
@pacificdragon thanks for the report ! 

> It started happening when scipy version got upgraded from 1.7.3 to 1.10.0.

I wonder how the chain goes from sklearn to scipy ? If you may have seen that `PrecisionRecallCurve` is just calling sklearn under the hood:
https://github.com/pytorch/ignite/blob/a720dfa7dee9dc0a8ad2a7323e6c33f101aca9c7/ignite/contrib/metrics/precision_recall_curve.py#L18

So, does it mean that sklearn has a bug which depends on scipy ?

**Comment by theory-in-progress** [comment] 2023-02-08 14:21
Hi @vfdev-5 

- Reproduced the issue locally
- The "Got" result is Correct
- [Scikit Learn Precision Recall Curve](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_curve.html#sklearn.metrics.precision_recall_curve)
- [Source Code of Scikit Learn Precision Recall Curve](https://github.com/scikit-learn/scikit-learn/blob/7db5b6a98/sklearn/metrics/_ranking.py#L797)
- According to scikit learn, `n_thresholds = len(np.unique(y_pred))`
- scipy version 1.7.3 too results the same results as the "Got"
- Reverted Back to the commit from before 18th Jan and Using a new Virtual Env recreated the problem, gives the same results

Proposed way to solve - 

- The "Got" result is correct so we sould probably update the DocTest

**Comment by vfdev-5** [comment] 2023-02-08 14:29
@theory-in-progress thanks for your investigation !

> Reverted Back to the commit from before 18th Jan and Using a new Virtual Env recreated the problem, gives the same results

What result did you get ? Did you get a failure or test is passing ?

> The "Got" result is Correct

How do you know that ?

I still do not quite understand the main reason why the test has started to fail. Can you give more details on that ?

**Comment by guptaaryan16** [comment] 2023-02-08 21:20
I guess @theory-in-progress and @pacificdragon are both correct. Actually on 18 Jan, Sklearn moved itself scipy from 1.7.3 to 1.10.0 as the minimum support version 
https://github.com/scikit-learn/scikit-learn/commit/d60af3de412cbd9f7504beb14350b942ae460703

**Comment by vfdev-5** [comment] 2023-02-08 21:46
@guptaaryan16 thanks as well for your findings !

Can you guys check the following: install scipy=1.7.3 and the latest scikit-learn and run our test example without using ignite but using pure scikit-learn code to compute precision recall curve. Next, install scipy=1.10 and rerun the same code. So, do we have the same results or not ? If results are the same then we can just update our test with respect of the expected output. If results are not the same, then there is an issue inside sklearn.

Please also post here the code and the outputs. Thanks !

**Comment by theory-in-progress** [comment] 2023-02-09 12:14
- The failure happens with [Precision Recall Curve](https://pytorch.org/ignite/generated/ignite.contrib.metrics.PrecisionRecallCurve.html)
- This was an issue with `scikit-learn` which was resolved in their [PR - FIX compute precision-recall at 100% recall](https://github.com/scikit-learn/scikit-learn/pull/23214)
	- This was because `precision_recall_curve()` was not returning the full curve at high recall
	- Read more about the issue [here](https://github.com/scikit-learn/scikit-learn/issues/23213)
- This Issue persisted Till now because `scikit-learn==1.0.2`  was being installed and the change in Precision Recall Curve was in version `scikit-learn==1.1.1`
- Possible reason why this was happening - Python 3.7 was being used, when that changed and [3.7 was dropped from CI](https://github.com/pytorch/ignite/pull/2836) 

Changes - 
- Updated the Doctests to match with Scikit-Learn

**Closed** 2023-02-09 15:24 UTC
Labels: bug, help wanted, good first issue, ci
